//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTGarmentAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TTGarmentAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Master.
        /// </summary>
        public static string BannerMaster {
            get {
                return ResourceManager.GetString("BannerMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductCode.
        /// </summary>
        public static string CodeColumn {
            get {
                return ResourceManager.GetString("CodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt Barcode.
        /// </summary>
        public static string EncryptBarcode {
            get {
                return ResourceManager.GetString("EncryptBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallary Manager.
        /// </summary>
        public static string GallaryManager {
            get {
                return ResourceManager.GetString("GallaryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Category.
        /// </summary>
        public static string MediaCategoryMaster {
            get {
                return ResourceManager.GetString("MediaCategoryMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductName.
        /// </summary>
        public static string NameColumn {
            get {
                return ResourceManager.GetString("NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Master.
        /// </summary>
        public static string NotificationMaster {
            get {
                return ResourceManager.GetString("NotificationMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Master.
        /// </summary>
        public static string OrderMaster {
            get {
                return ResourceManager.GetString("OrderMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductPoints.
        /// </summary>
        public static string PointsColumn {
            get {
                return ResourceManager.GetString("PointsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Ledger.
        /// </summary>
        public static string PointsLedger {
            get {
                return ResourceManager.GetString("PointsLedger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductImage.
        /// </summary>
        public static string ProductImage {
            get {
                return ResourceManager.GetString("ProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Manager.
        /// </summary>
        public static string ProductManager {
            get {
                return ResourceManager.GetString("ProductManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion Manager.
        /// </summary>
        public static string PromotionView {
            get {
                return ResourceManager.GetString("PromotionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductQuantity.
        /// </summary>
        public static string QuantityColumn {
            get {
                return ResourceManager.GetString("QuantityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Retailer.
        /// </summary>
        public static string RegisteredRetailer {
            get {
                return ResourceManager.GetString("RegisteredRetailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductSize.
        /// </summary>
        public static string SizeColumn {
            get {
                return ResourceManager.GetString("SizeColumn", resourceCulture);
            }
        }
    }
}
